# Generated by Django 3.2.5 on 2022-02-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_student_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='student',
            name='strand',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
