# Generated by Django 3.2.5 on 2022-02-21 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_studentapplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplied',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applied_school', to='accounts.school'),
        ),
    ]
