# Generated by Django 3.2.5 on 2022-02-23 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_studentapplied_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentapplied',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='studentapplied',
            name='status',
            field=models.CharField(blank=True, default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplied',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_applied', to='accounts.student'),
        ),
    ]
