# Generated by Django 3.2.5 on 2022-02-23 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20220223_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplied',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_applied', to='accounts.student'),
        ),
    ]
