# Generated by Django 3.2.5 on 2022-03-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20220224_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplied',
            name='datetime_created',
            field=models.DateTimeField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentapplied',
            name='datetime_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplied',
            name='is_seen_by_school',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentapplied',
            name='is_seen_by_student',
            field=models.BooleanField(default=False),
        ),
    ]
