# Generated by Django 3.2.5 on 2022-02-01 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20220201_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_exam', to='accounts.school')),
            ],
        ),
    ]
