# Generated by Django 3.2.5 on 2022-02-01 07:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='file',
        ),
        migrations.AddField(
            model_name='exam',
            name='csv_file',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='file'),
        ),
    ]
