# Generated by Django 3.2.5 on 2022-02-01 08:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_exam_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='csv_file',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
