# Generated by Django 3.2.5 on 2022-02-01 08:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_exam_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='csv_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='csv'),
        ),
    ]
