# Generated by Django 3.2.5 on 2022-02-01 08:46

from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_exam_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to=school.models.Exam.path),
        ),
    ]
