# Generated by Django 3.2.5 on 2022-02-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_school_user'),
        ('school', '0008_alter_exam_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_exam', to='accounts.school'),
        ),
    ]
