# Generated by Django 3.2.5 on 2022-02-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_question_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='logo',
            new_name='image',
        ),
    ]
