# Generated by Django 3.2.5 on 2022-02-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='text',
            new_name='option_text',
        ),
    ]
