# Generated by Django 3.2.5 on 2022-02-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_rename_text_option_option_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='option_text',
            new_name='text',
        ),
    ]
