# Generated by Django 3.2.5 on 2022-02-03 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_rename_option_text_option_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Option',
            new_name='Choice',
        ),
    ]
