# Generated by Django 3.2.5 on 2022-02-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_choice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
