# Generated by Django 3.2.5 on 2022-02-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_alter_choice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='time_limit',
            field=models.TimeField(null=True),
        ),
    ]
