# Generated by Django 3.2.5 on 2022-02-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_alter_exam_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(0, 'multipleChoice'), (1, 'checkbox'), (2, 'fillInTheBlank')], default=0),
        ),
    ]
