# Generated by Django 3.2.5 on 2022-02-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time_limit',
            field=models.CharField(default='00:00', max_length=10),
        ),
    ]
