# Generated by Django 3.2.5 on 2022-02-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_alter_exam_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='total_questions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
