# Generated by Django 3.2.5 on 2022-02-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_subject_total_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(0, 'multipleChoice'), (1, 'checkbox'), (2, 'fillInTheBlank'), (4, 'trueOrFalse')], default=0),
        ),
    ]
