# Generated by Django 3.2.5 on 2022-03-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='current_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
