# Generated by Django 3.2.5 on 2022-05-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_subject_current_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(0, 'multipleChoice'), (1, 'checkbox'), (2, 'fillInTheBlank'), (3, 'rating')], default=0),
        ),
    ]
