# Generated by Django 3.2.5 on 2022-05-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='spreadsheet_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
