# Generated by Django 3.2.5 on 2022-02-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_result_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserecommended',
            options={'verbose_name': 'Course Recommend'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-id'], 'verbose_name': 'Exam Result'},
        ),
        migrations.AlterModelOptions(
            name='resultdetails',
            options={'verbose_name': 'Result Detail'},
        ),
    ]
