# Generated by Django 3.2.5 on 2022-02-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20220215_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserecommended',
            name='r2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
