# Generated by Django 3.2.5 on 2022-02-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_courserecommended_r2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserecommended',
            options={'ordering': ['-r2'], 'verbose_name': 'Course Recommend'},
        ),
    ]
