# Generated by Django 3.2.5 on 2022-03-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_courserecommended_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserecommended',
            options={'ordering': ['id'], 'verbose_name': 'Course Recommend'},
        ),
        migrations.RemoveField(
            model_name='courserecommended',
            name='r2',
        ),
    ]
