# Generated by Django 3.2.5 on 2022-03-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20220314_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserecommended',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
