# Generated by Django 3.2.5 on 2022-03-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_courserecommended_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserecommended',
            name='formula',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='courserecommended',
            name='regression_model',
            field=models.CharField(default='', max_length=255),
        ),
    ]
