# Generated by Django 3.2.5 on 2022-03-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20220317_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserecommended',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='courserecommended',
            name='regression_model',
        ),
        migrations.AddField(
            model_name='result',
            name='formula',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='result',
            name='regression_model',
            field=models.CharField(default='', max_length=255),
        ),
    ]
