# Generated by Django 3.2.5 on 2022-05-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20220317_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultdetails',
            name='overall',
            field=models.IntegerField(default=0),
        ),
    ]
