# Generated by Django 3.2.5 on 2022-05-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_resultdetails_overall'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='tab_switch',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='result',
            name='video',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
